#############################################################################
# Makefile for building: Lijusi
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Sep 29 16:48:30 2010
# Project:  Lijusi.pro
# Template: app
# Command: $(QMAKE) -o Makefile Lijusi.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Lijusi.h
SOURCES = Lijusi.cpp \
		main.cpp \
		build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c \
		build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp
OBJECTS = Lijusi.o \
		main.o \
		CMakeCCompilerId.o \
		CMakeCXXCompilerId.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_Lijusi.cpp
OBJMOC = moc_Lijusi.o
DIST	   = Lijusi.pro
QMAKE_TARGET = Lijusi
DESTDIR  = 
TARGET   = Lijusi

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: Lijusi.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile Lijusi.pro
qmake: 
	@$(QMAKE) -o Makefile Lijusi.pro

dist: 
	@mkdir -p .tmp/Lijusi && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/Lijusi/ && ( cd `dirname .tmp/Lijusi` && $(TAR) Lijusi.tar Lijusi && $(GZIP) Lijusi.tar ) && $(MOVE) `dirname .tmp/Lijusi`/Lijusi.tar.gz . && $(DEL_FILE) -r .tmp/Lijusi

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

Lijusi.o: Lijusi.cpp Lijusi.h

main.o: main.cpp Lijusi.h

CMakeCCompilerId.o: build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o CMakeCCompilerId.o build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c

CMakeCXXCompilerId.o: build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMakeCXXCompilerId.o build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp

moc_Lijusi.o: moc_Lijusi.cpp  Lijusi.h 

moc_Lijusi.cpp: $(MOC) Lijusi.h
	$(MOC) Lijusi.h -o moc_Lijusi.cpp

####### Install

install:  

uninstall:  

